import { readFileSync, writeFileSync } from "node:fs";

// Icon map mirroring src/components/numind/icon.tsx (emoji char -> lucide name).
const EMOJI_MAP = {
  "➡": "ArrowRight",
  "☀": "Sun",
  "☁": "Cloud",
  "☆": "Star",
  "✏": "Pencil",
  "✓": "Check",
  "✕": "X",
  "❄": "Snowflake",
  "❓": "CircleQuestionMark",
  "❤": "Heart",
  "✨": "Sparkles",
  "☕": "Coffee",
  "⚠": "TriangleAlert",
  "⚡": "Zap",
  "⚙": "Settings",
  "⛄": "Snowflake",
  "⛅": "CloudSun",
  "⛲": "Droplets",
  "⭐": "Star",
  "🃏": "Sparkles",
  "🆘": "LifeBuoy",
  "🌅": "Sunrise",
  "🌈": "Rainbow",
  "🌊": "Waves",
  "🌌": "MoonStar",
  "🌍": "Globe",
  "🌙": "Moon",
  "🌝": "Circle",
  "🌞": "Sun",
  "🌟": "Sparkles",
  "🌤": "CloudSun",
  "🌥": "CloudFog",
  "🌧": "CloudRain",
  "🌬": "Wind",
  "🌱": "Sprout",
  "🌲": "TreePine",
  "🌳": "Trees",
  "🌴": "TreePalm",
  "🌵": "Sprout",
  "🌷": "Flower2",
  "🌸": "Flower2",
  "🌹": "Flower2",
  "🌺": "Flower2",
  "🌻": "Flower2",
  "🌼": "Flower2",
  "🌾": "Wheat",
  "🌿": "Sprout",
  "🍀": "Clover",
  "🍁": "Leaf",
  "🍂": "Leaf",
  "🍃": "Leaf",
  "🍅": "Circle",
  "🍇": "Circle",
  "🍉": "Circle",
  "🍊": "Citrus",
  "🍋": "Citrus",
  "🍎": "Apple",
  "🍫": "Candy",
  "🍵": "Coffee",
  "🎀": "Gift",
  "🎁": "Gift",
  "🎃": "Circle",
  "🎄": "TreePine",
  "🎈": "Balloon",
  "🎉": "PartyPopper",
  "🎓": "GraduationCap",
  "🎖": "Award",
  "🎚": "SlidersHorizontal",
  "🎟": "Ticket",
  "🎡": "FerrisWheel",
  "🎨": "Palette",
  "🎩": "GraduationCap",
  "🎬": "Clapperboard",
  "🎮": "Gamepad2",
  "🎯": "Target",
  "🎵": "Music",
  "🎶": "Music",
  "🏃": "Footprints",
  "🏅": "Medal",
  "🏆": "Trophy",
  "🏖": "Umbrella",
  "🏝": "TreePalm",
  "🏠": "Home",
  "🏡": "Home",
  "🏮": "Lamp",
  "🐘": "Circle",
  "🐚": "Shell",
  "🐝": "Bug",
  "🐠": "Fish",
  "🐢": "Turtle",
  "🐦": "Bird",
  "🐬": "Fish",
  "🐰": "Rabbit",
  "🐳": "Fish",
  "👋": "Hand",
  "👏": "HandHeart",
  "👟": "Footprints",
  "👤": "UserRound",
  "💆": "PersonStanding",
  "💌": "Mail",
  "💐": "Flower2",
  "💙": "Heart",
  "💚": "Heart",
  "💛": "Heart",
  "💜": "Heart",
  "💤": "Moon",
  "💧": "Droplets",
  "💪": "Dumbbell",
  "💫": "Sparkles",
  "💬": "MessageCircle",
  "💭": "MessageSquareText",
  "📅": "Calendar",
  "📊": "ChartColumn",
  "📌": "Pin",
  "📖": "BookOpen",
  "📚": "BookOpen",
  "📝": "NotebookPen",
  "📱": "Smartphone",
  "🔁": "RefreshCcw",
  "🔇": "VolumeX",
  "🔎": "Search",
  "🔒": "Lock",
  "🔔": "Bell",
  "🔥": "Flame",
  "🕊": "Bird",
  "🕶": "Glasses",
  "🖐": "Hand",
  "🖥": "Monitor",
  "🖼": "Image",
  "🗑": "Trash2",
  "😀": "Smile",
  "😁": "SmilePlus",
  "😄": "Smile",
  "😇": "Smile",
  "😊": "Smile",
  "😌": "Smile",
  "😐": "Meh",
  "😔": "Frown",
  "😴": "Moon",
  "🙂": "Smile",
  "🙈": "Eye",
  "🙌": "HandHeart",
  "🚪": "DoorOpen",
  "🚶": "Footprints",
  "🛁": "Bath",
  "🛡": "Shield",
  "🟤": "Circle",
  "🤍": "Heart",
  "🤔": "CircleQuestionMark",
  "🤖": "Bot",
  "🤗": "HandHeart",
  "🤝": "Handshake",
  "🤸": "PersonStanding",
  "🥀": "Flower2",
  "🥑": "Citrus",
  "🥕": "Carrot",
  "🥗": "Salad",
  "🥛": "Milk",
  "🥰": "Smile",
  "🥳": "PartyPopper",
  "🦉": "Bird",
  "🦊": "Cat",
  "🦋": "Flower2",
  "🦌": "Circle",
  "🦢": "Bird",
  "🧘": "PersonStanding",
  "🧠": "Brain",
  "🧢": "Circle",
  "🧩": "Puzzle",
  "🧸": "Gift",
  "🧺": "ShoppingBasket",
  "🪑": "Armchair",
  "🪨": "Mountain",
  "🫁": "Activity",
  "🫖": "Coffee",
  "🫥": "Circle",
  "🫧": "Sparkles",
};

const EMOJI_RE = new RegExp(`[${Object.keys(EMOJI_MAP).join("")}]`, "gu");

const toIcon = (s) =>
  s
    .replace(/\uFE0F/g, "")
    .replace(EMOJI_RE, (m) => EMOJI_MAP[m] ?? "");
const strip = (s) => s.replace(EMOJI_RE, "").replace(/^\s+/, "").replace(/^([^a-zA-Z])+/, "");

let path = "src/lib/mock-data.ts";
let text = readFileSync(path, "utf8");
let before = text;

// 1. `emoji:"..."` / `avatar:"..."` field values -> icon names
text = text.replace(/(emoji|avatar)\s*:\s*"([^"]*)"/g, (whole, key, val) => {
  const conv = toIcon(val);
  return conv === val ? whole : `${key}: "${conv}"`;
});

// 2. compound label strings that embed emoji prefixes (mode/mood) -> text-label only
text = text.replace(/(mode|mood)\s*:\s*"([^"]*)"/g, (whole, key, val) => {
  const conv = strip(val);
  return conv === val ? whole : `${key}: "${conv}"`;
});

if (text !== before) {
  writeFileSync(path, text, "utf8");
  console.log(`updated ${path}`);
} else {
  console.log(`no change ${path}`);
}