/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppFocusRouteImport } from './routes/app.focus'
import { Route as AppMindGymRouteImport } from './routes/app.mind-gym'
import { Route as AppNumiRouteImport } from './routes/app.numi'
import { Route as AppQuestRouteImport } from './routes/app.quest'
import { Route as AppResetRouteImport } from './routes/app.reset'
import { Route as AppWellnessRouteImport } from './routes/app.wellness'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFocusRoute = AppFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AppRoute,
} as any)
const AppMindGymRoute = AppMindGymRouteImport.update({
  id: '/mind-gym',
  path: '/mind-gym',
  getParentRoute: () => AppRoute,
} as any)
const AppNumiRoute = AppNumiRouteImport.update({
  id: '/numi',
  path: '/numi',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestRoute = AppQuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => AppRoute,
} as any)
const AppResetRoute = AppResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AppRoute,
} as any)
const AppWellnessRoute = AppWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/focus': typeof AppFocusRoute
  '/app/mind-gym': typeof AppMindGymRoute
  '/app/numi': typeof AppNumiRoute
  '/app/quest': typeof AppQuestRoute
  '/app/reset': typeof AppResetRoute
  '/app/wellness': typeof AppWellnessRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/focus': typeof AppFocusRoute
  '/app/mind-gym': typeof AppMindGymRoute
  '/app/numi': typeof AppNumiRoute
  '/app/quest': typeof AppQuestRoute
  '/app/reset': typeof AppResetRoute
  '/app/wellness': typeof AppWellnessRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/focus': typeof AppFocusRoute
  '/app/mind-gym': typeof AppMindGymRoute
  '/app/numi': typeof AppNumiRoute
  '/app/quest': typeof AppQuestRoute
  '/app/reset': typeof AppResetRoute
  '/app/wellness': typeof AppWellnessRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/focus'
    | '/app/mind-gym'
    | '/app/numi'
    | '/app/quest'
    | '/app/reset'
    | '/app/wellness'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/focus'
    | '/app/mind-gym'
    | '/app/numi'
    | '/app/quest'
    | '/app/reset'
    | '/app/wellness'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/focus'
    | '/app/mind-gym'
    | '/app/numi'
    | '/app/quest'
    | '/app/reset'
    | '/app/wellness'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/focus': {
      id: '/app/focus'
      path: '/focus'
      fullPath: '/app/focus'
      preLoaderRoute: typeof AppFocusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mind-gym': {
      id: '/app/mind-gym'
      path: '/mind-gym'
      fullPath: '/app/mind-gym'
      preLoaderRoute: typeof AppMindGymRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/numi': {
      id: '/app/numi'
      path: '/numi'
      fullPath: '/app/numi'
      preLoaderRoute: typeof AppNumiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quest': {
      id: '/app/quest'
      path: '/quest'
      fullPath: '/app/quest'
      preLoaderRoute: typeof AppQuestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reset': {
      id: '/app/reset'
      path: '/reset'
      fullPath: '/app/reset'
      preLoaderRoute: typeof AppResetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wellness': {
      id: '/app/wellness'
      path: '/wellness'
      fullPath: '/app/wellness'
      preLoaderRoute: typeof AppWellnessRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFocusRoute: typeof AppFocusRoute
  AppMindGymRoute: typeof AppMindGymRoute
  AppNumiRoute: typeof AppNumiRoute
  AppQuestRoute: typeof AppQuestRoute
  AppResetRoute: typeof AppResetRoute
  AppWellnessRoute: typeof AppWellnessRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFocusRoute: AppFocusRoute,
  AppMindGymRoute: AppMindGymRoute,
  AppNumiRoute: AppNumiRoute,
  AppQuestRoute: AppQuestRoute,
  AppResetRoute: AppResetRoute,
  AppWellnessRoute: AppWellnessRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
