import {
  Activity,
  Apple,
  Armchair,
  ArrowRight,
  Award,
  Balloon,
  Bath,
  Bell,
  Bird,
  BookOpen,
  Bot,
  Brain,
  Bug,
  Calendar,
  Candy,
  Carrot,
  Cat,
  ChartColumn,
  Check,
  Circle,
  CircleCheck,
  CircleQuestionMark,
  Citrus,
  Clapperboard,
  Cloud,
  CloudFog,
  CloudRain,
  CloudSun,
  Clover,
  Coffee,
  CupSoda,
  Dog,
  DoorOpen,
  Droplets,
  Dumbbell,
  Eye,
  FerrisWheel,
  Fish,
  Flame,
  Flower2,
  Footprints,
  Frown,
  Gamepad2,
  Gem,
  Ghost,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Hand,
  HandHeart,
  Handshake,
  Heart,
  Home,
  Image,
  Lamp,
  Leaf,
  LifeBuoy,
  Lock,
  Mail,
  Medal,
  Meh,
  MessageCircle,
  MessageSquareText,
  Milk,
  Monitor,
  Moon,
  MoonStar,
  Mountain,
  Music,
  NotebookPen,
  Palette,
  PartyPopper,
  Pencil,
  PersonStanding,
  Pin,
  Play,
  Puzzle,
  Rabbit,
  Rainbow,
  RefreshCcw,
  Salad,
  Search,
  Settings,
  Shell,
  Shield,
  ShoppingBasket,
  SlidersHorizontal,
  Smartphone,
  Smile,
  SmilePlus,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Sunrise,
  Target,
  Ticket,
  ToyBrick,
  Trash2,
  TreePalm,
  TreePine,
  Trees,
  TriangleAlert,
  Trophy,
  Turtle,
  Umbrella,
  UserRound,
  Volume2,
  VolumeX,
  Waves,
  Wheat,
  Wind,
  X,
  Zap,
Timer,
  type LucideIcon,
} from "lucide-react";

/**
 * Central icon registry.
 *
 * Every `Icon` in the app renders an SVG from `lucide-react`. A symbol token
 * can be either:
 *  - an icon name ("Sun"), the format used by new code and mock data, or
 *  - a legacy emoji character (🌞) still stored in the database / older seed
 *    data. `resolveIcon` maps emoji → the closest lucide icon so nothing ever
 *    renders as a platform-dependent emoji glyph.
 */

export const ICONS = {
  Activity,
  Apple,
  Armchair,
  ArrowRight,
  Award,
  Balloon,
  Bath,
  Bell,
  Bird,
  BookOpen,
  Bot,
  Brain,
  Bug,
  Calendar,
  Candy,
  Carrot,
  Cat,
  ChartColumn,
  Check,
  Circle,
  CircleCheck,
  CircleQuestionMark,
  Citrus,
  Clapperboard,
  Cloud,
  CloudFog,
  CloudRain,
  CloudSun,
  Clover,
  Coffee,
  CupSoda,
  Dog,
  DoorOpen,
  Droplets,
  Dumbbell,
  Eye,
  FerrisWheel,
  Fish,
  Flame,
  Flower2,
  Footprints,
  Frown,
  Gamepad2,
  Gem,
  Ghost,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Hand,
  HandHeart,
  Handshake,
  Heart,
  Home,
  Image,
  Lamp,
  Leaf,
  LifeBuoy,
  Lock,
  Mail,
  Medal,
  Meh,
  MessageCircle,
  MessageSquareText,
  Milk,
  Monitor,
  Moon,
  MoonStar,
  Mountain,
  Music,
  NotebookPen,
  Palette,
  PartyPopper,
  Pencil,
  PersonStanding,
  Pin,
  Play,
  Puzzle,
  Rabbit,
  Rainbow,
  RefreshCcw,
  Salad,
  Search,
  Settings,
  Shell,
  Shield,
  ShoppingBasket,
  SlidersHorizontal,
  Smartphone,
  Smile,
  SmilePlus,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Sunrise,
  Target,
  Ticket,
Timer,
  ToyBrick,
  Trash2,
  TreePalm,
  TreePine,
  Trees,
  TriangleAlert,
  Trophy,
  Turtle,
  Umbrella,
  UserRound,
  Volume2,
  VolumeX,
  Waves,
  Wheat,
  Wind,
  X,
  Zap,
} satisfies Record<string, LucideIcon>;

/** Legacy emoji character → lucide icon name. */
const EMOJI_MAP: Record<string, keyof typeof ICONS> = {
  "➡": "ArrowRight",
  "☀": "Sun",
  "☁": "Cloud",
  "☆": "Star",
  "✏": "Pencil",
  "✓": "Check",
  "✕": "X",
  "❄": "Snowflake",
  "❓": "CircleQuestionMark",
  "❤": "Heart",
  "✨": "Sparkles",
  "☕": "Coffee",
  "⚠": "TriangleAlert",
  "⚡": "Zap",
  "⚙": "Settings",
  "⛄": "Snowflake",
  "⛅": "CloudSun",
  "⛲": "Droplets",
  "⭐": "Star",
  "🃏": "Sparkles",
  "🆘": "LifeBuoy",
  "🌅": "Sunrise",
  "🌈": "Rainbow",
  "🌊": "Waves",
  "🌌": "MoonStar",
  "🌍": "Globe",
  "🌙": "Moon",
  "🌝": "Circle",
  "🌞": "Sun",
  "🌟": "Sparkles",
  "🌤": "CloudSun",
  "🌥": "CloudFog",
  "🌧": "CloudRain",
  "🌬": "Wind",
  "🌱": "Sprout",
  "🌲": "TreePine",
  "🌳": "Trees",
  "🌴": "TreePalm",
  "🌵": "Sprout",
  "🌷": "Flower2",
  "🌸": "Flower2",
  "🌹": "Flower2",
  "🌺": "Flower2",
  "🌻": "Flower2",
  "🌼": "Flower2",
  "🌾": "Wheat",
  "🌿": "Sprout",
  "🍀": "Clover",
  "🍁": "Leaf",
  "🍂": "Leaf",
  "🍃": "Leaf",
  "🍅": "Circle",
  "🍇": "Circle",
  "🍉": "Circle",
  "🍊": "Citrus",
  "🍋": "Citrus",
  "🍎": "Apple",
  "🍫": "Candy",
  "🍵": "Coffee",
  "🎀": "Gift",
  "🎁": "Gift",
  "🎃": "Circle",
  "🎄": "TreePine",
  "🎈": "Balloon",
  "🎉": "PartyPopper",
  "🎓": "GraduationCap",
  "🎖": "Award",
  "🎚": "SlidersHorizontal",
  "🎟": "Ticket",
  "🎡": "FerrisWheel",
  "🎨": "Palette",
  "🎩": "GraduationCap",
  "🎬": "Clapperboard",
  "🎮": "Gamepad2",
  "🎯": "Target",
  "⏱": "Timer",
  "🎵": "Music",
  "🎶": "Music",
  "🏃": "Footprints",
  "🏅": "Medal",
  "🏆": "Trophy",
  "🏖": "Umbrella",
  "🏝": "TreePalm",
  "🏠": "Home",
  "🏡": "Home",
  "🏮": "Lamp",
  "🐘": "Circle",
  "🐚": "Shell",
  "🐝": "Bug",
  "🐠": "Fish",
  "🐢": "Turtle",
  "🐦": "Bird",
  "🐬": "Fish",
  "🐰": "Rabbit",
  "🐳": "Fish",
  "👋": "Hand",
  "👏": "HandHeart",
  "👟": "Footprints",
  "👤": "UserRound",
  "💆": "PersonStanding",
  "💌": "Mail",
  "💐": "Flower2",
  "💙": "Heart",
  "💚": "Heart",
  "💛": "Heart",
  "💜": "Heart",
  "💤": "Moon",
  "💧": "Droplets",
  "💪": "Dumbbell",
  "💫": "Sparkles",
  "💬": "MessageCircle",
  "💭": "MessageSquareText",
  "📅": "Calendar",
  "📊": "ChartColumn",
  "📌": "Pin",
  "📖": "BookOpen",
  "📚": "BookOpen",
  "📝": "NotebookPen",
  "📱": "Smartphone",
  "🔁": "RefreshCcw",
  "🔇": "VolumeX",
  "🔎": "Search",
  "🔒": "Lock",
  "🔔": "Bell",
  "🔥": "Flame",
  "🕊": "Bird",
  "🕶": "Glasses",
  "🖐": "Hand",
  "🖥": "Monitor",
  "🖼": "Image",
  "🗑": "Trash2",
  "😀": "Smile",
  "😁": "SmilePlus",
  "😄": "Smile",
  "😇": "Smile",
  "😊": "Smile",
  "😌": "Smile",
  "😐": "Meh",
  "😔": "Frown",
  "😴": "Moon",
  "🙂": "Smile",
  "🙈": "Eye",
  "🙌": "HandHeart",
  "🚪": "DoorOpen",
  "🚶": "Footprints",
  "🛁": "Bath",
  "🛡": "Shield",
  "🟤": "Circle",
  "🤍": "Heart",
  "🤔": "CircleQuestionMark",
  "🤖": "Bot",
  "🤗": "HandHeart",
  "🤝": "Handshake",
  "🤸": "PersonStanding",
  "🥀": "Flower2",
  "🥑": "Citrus",
  "🥕": "Carrot",
  "🥗": "Salad",
  "🥛": "Milk",
  "🥰": "Smile",
  "🥳": "PartyPopper",
  "🦉": "Bird",
  "🦊": "Cat",
  "🦋": "Flower2",
  "🦌": "Circle",
  "🦢": "Bird",
  "🧘": "PersonStanding",
  "🧠": "Brain",
  "🧢": "Circle",
  "🧩": "Puzzle",
  "🧸": "Gift",
  "🧺": "ShoppingBasket",
  "🪑": "Armchair",
  "🪨": "Mountain",
  "🫁": "Activity",
  "🫖": "Coffee",
  "🫥": "Circle",
  "🫧": "Sparkles",
};

const VARIATION_SELECTOR = "\uFE0F";

/** Resolve any symbol token (legacy emoji char or lucide icon name). */
export function resolveIcon(symbol?: string | null): LucideIcon | null {
  if (!symbol) return null;
  const t = symbol.trim();
  if (ICONS[t]) return ICONS[t] as LucideIcon;
  if (EMOJI_MAP[t]) return ICONS[EMOJI_MAP[t] as keyof typeof ICONS] as LucideIcon;
  const stripped = t.replaceAll(VARIATION_SELECTOR, "");
  if (stripped !== t) {
    if (ICONS[stripped]) return ICONS[stripped] as LucideIcon;
    if (EMOJI_MAP[stripped])
      return ICONS[EMOJI_MAP[stripped] as keyof typeof ICONS] as LucideIcon;
  }
  return null;
}

/**
 * Renders a symbol token as an SVG (via lucide-react).
 *
 * @param symbol      icon name ("Sun") or legacy emoji character ("🌞")
 * @param size        width/height in px (or any CSS size lucide accepts)
 * @param strokeWidth stroke width
 * @param className   extra classes
 * @param fill        fill the glyph with currentColor (for solid stars/hearts)
 */
export function Icon({
  symbol,
  size = 20,
  strokeWidth,
  className,
  fill,
}: {
  symbol?: string | null;
  size?: number | string;
  strokeWidth?: number | string;
  className?: string;
  fill?: boolean;
}) {
  const Cmp = resolveIcon(symbol);
  if (!Cmp) return null;
  return (
    <Cmp
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      fill={fill ? "currentColor" : "none"}
      aria-hidden="true"
    />
  );
}

export type { LucideIcon };